name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Triggers when a tag like 'v1.0.0' is pushed
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  build-and-publish:
    name: Build and Publish sfeos-tools
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
